version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: back-end/..
      dockerfile: back-end/Dockerfile
    env_file:
      - back-end/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: frontend/..
      dockerfile: front-end/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080
volumes:
  pgdata:
